services:
  postgres:
    image: postgres:15.10-alpine3.21
    ports:
      - '0.0.0.0:${DB_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASS}'
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ['CMD', 'postgresql', 'ping']
  core-ecommerce:
    container_name: core-ecommerce
    build:
      context: .
    ports:
      - "3000:3000"